# NumPy Practice

This notebook gives you hands-on practice with the core NumPy skills from `01_Introduction_to_Numpy.ipynb`. You will create arrays in several ways, inspect their properties, reshape and index into them, and apply arithmetic operations, both element-wise and along a specific axis. Work through the challenges in order, as later ones build on earlier results.

---

## Starter Code

In [1]:
# Import NumPy, run this cell first
import numpy as np

## Part 1: Creating Arrays

### Challenge 1: Array from a list

Create a NumPy array from the following Python list:

```python
my_list = [1, 2, 5, 6, 8]
```

Print the array and its `dtype`.

In [5]:
# YOUR CODE HERE
my_list = [1, 2, 5, 6, 8]
arr = np.array(my_list)
print(arr)
print(arr.dtype)

[1 2 5 6 8]
int64


### Challenge 2: Range array

Create a NumPy array containing the integers from **1 to 10** (inclusive).

In [10]:
# YOUR CODE HERE
arr= np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### Challenge 3: Float range array

Create a NumPy array from **0 to 5** with a step size of **0.2**.

In [11]:
# YOUR CODE HERE
arr = np.arange(0, 5, 0.2)
print(arr)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]


### Challenge 4: Random array

Create a NumPy array with shape **(2, 3)** filled with random values between 0 and 1.

In [13]:
# YOUR CODE HERE
arr = np.random.rand(2, 3)
print(arr)

[[0.50857983 0.88429213 0.16357141]
 [0.77977835 0.52623407 0.44397012]]


---

## Part 2: Manipulating Arrays

### Challenge 5: Array with mixed-type input

Create a NumPy array from the values `(1, 3, '4', 7, 12, '0')`. Force the data type to **integer** using the `dtype` parameter.

> Notice that the string values `'4'` and `'0'` are silently cast to integers. NumPy arrays are homogeneous: all elements must share the same type.

In [14]:
# YOUR CODE HERE
# dtype=int forces the string values '4' and '0' to be cast to integers
my_array = np.array((1, 3, "4", 7, 12, "0"), dtype=int)
print(my_array)


[ 1  3  4  7 12  0]


### Challenge 6: Inspect dtype and shape

Using the array you created in Challenge 5, check:
- The **data type** of the elements
- The **shape** of the array

In [18]:
# YOUR CODE HERE
print(my_array.dtype)
my_array.shape

int64


(6,)

### Challenge 7: Update a value by index

Update the **4th element** (index 3) of the array from Challenge 5 to the value `30`.

In [19]:
# YOUR CODE HERE
my_array[3] = 30
print(my_array)

[ 1  3  4 30 12  0]


### Challenge 8: Reshape to a 2×3 matrix

Reshape the array from Challenge 7 into a **2-row, 3-column** matrix. Print the result.

In [22]:
# YOUR CODE HERE
my_array = my_array.reshape(2, 3)
print(my_array)

[[ 1  3  4]
 [30 12  0]]


### Challenge 9: Row-wise addition

Using the 2×3 matrix from Challenge 8:
- Add **8** to every value in the **first row**
- Add **12** to every value in the **second row**

> Hint: index the rows and assign back in place.

In [29]:
# YOUR CODE HERE
my_array[0] = my_array[0] + 8
my_array[1] = my_array[1] + 12
print(my_array)

[[ 9 11 12]
 [42 24 12]]


### Challenge 10: Column-wise multiplication

Multiply the columns of your matrix:
- **First column** × 2
- **Second column** × 3
- **Third column** × 4

> Hint: you can do this in one line using broadcasting with a 1D array `[2, 3, 4]`.

In [30]:
# YOUR CODE HERE
my_array = my_array * np.array([2, 3, 4])
print(my_array)

[[18 33 48]
 [84 72 48]]


### Challenge 11: Row sums

Calculate the **sum of all values in each row** of your matrix. You should get two totals, one per row.

In [31]:
# YOUR CODE HERE
# axis=1 collapses the columns, giving one sum per row
row_sums = my_array.sum(axis=1)
print(row_sums)

[ 99 204]


### Challenge 12: Column maximums

Find the **largest value in each column** of your matrix. You should get three values, one per column.

In [33]:
# YOUR CODE HERE
# axis=0 collapses the rows, giving one maximum per column
col_max = my_array.max(axis=0)
print(col_max)

[84 72 48]


### Challenge 13: Index a single element

Extract the value from the **second column, first row** of your matrix.

> Reminder: NumPy uses `array[row, column]` indexing.

In [34]:
# YOUR CODE HERE
# NumPy uses [row, column] indexing: row 0, column 1
value = my_array[0, 1]
print(value)

33


### Challenge 14: Find the index of a specific value

Find the **index** of the value `48` in your matrix.

> Hint: use `np.where()`. Note that depending on how your array evolved across previous challenges, your value at a given position may differ, first check what values are currently in the matrix.

In [35]:
# YOUR CODE HERE
# first inspect the current matrix to see where 48 lives
print(my_array)
# np.where returns the row indices and column indices of every match
indices = np.where(my_array == 48)
print(indices)

[[18 33 48]
 [84 72 48]]
(array([0, 1]), array([2, 2]))
